name: Create Docker image and deploy

on:
  workflow_dispatch:
  push:
    branches: 
      - "**"
jobs:
  temp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    outputs:
      ref: ${{ github.repository.ref }}
      default_branch: ${{ github.event.repository.default_branch }}
  flow:
    uses: highsoft-corp/hs-platform-workflows/.github/workflows/flow_docker.yml@main
    secrets: inherit
    with:
      registry: ghcr.io
      folder_name: .
      image_name: ${{ github.repository }}
      #deploy_branch: master