name: Create Docker image and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  flow:
    uses: highsoft-corp/hs-platform-workflows/.github/workflows/flow_docker.yml@main
    secrets: inherit
    with:
      registry: ghcr.io
      folder_name: .
      image_name: ${{ github.repository }}